version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.8
  general: bjd2385/general@0.6.1


workflows:
  slack-roulette:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          auto-detect: true

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
